on:
  push:
    branches: ["master"]
  merge_group:
    branches: ["master"]

  workflow_dispatch:

name: Test, Build and Release
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: "11"
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.7.7"
    - name: Get dependencies
      run: flutter pub get
    - name: Build Android apk
      run: flutter build apk
    - name: Start release build
      run: flutter build appbundle

